### ISSUE TITLE
signature sort on patientReport

### ISSUE THREAD

**Issue by rbaertsch** [UCSC-MedBook/MedBook-PatientCare#1]
The rank sort should only consider upregulated signatures , not downregulated.

**Comment by mokolodi1** [comment]
Does that mean closer to the left of a waterfall plot? (aka higher values)

**Comment by rbaertsch** [comment]
Yes

**Comment by mokolodi1** [comment]
With https://github.com/UCSC-MedBook/MedBook-PatientCare/commit/f956bddc936edb28a4f9348cb5b6c96cd2ccbd99, cohort signatures are generated dynamically, meaning client-side sorting is easy. 

The current sort is the rank of the upregulated Pro sample, then the rank of the upregulated BL sample.
