### ISSUE TITLE
Move Limma/GSEA create promise code to server

### ISSUE THREAD

**Issue by mokolodi1** [UCSC-MedBook/MedBook-PatientCare#10]
Don't do it on the client...

**Comment by mokolodi1** [comment]
This works for now... This is a low priority bug.

**Comment by mokolodi1** [comment]
Job creation has been disabled and the offending code removed.

**Comment by e-t-k** [comment]
(That is to say, no new "Limma/GSEA" jobs can be run as we've split it out to have separate Limma and GSEA jobs, so the code in question no longer exists.)
