### ISSUE TITLE
inconsistent Normalization fields in Outlier analysis / possible bug?

### ISSUE THREAD

**Issue by e-t-k** [UCSC-MedBook/MedBook-PatientCare#14]
Outlier Analysis tool autodetected the following file as Quantile normalized counts log2(x+1) : 
RNA150410JA191-1-1522RV10uMJQ1.rsem.genes.norm_counts.hugo.tab 

Robert says (from glancing at the file's contents) that it is not in fact on a log scale and should be detected as Quantile normalized counts.

Similarly, on editSubmission page for another sample :
 RNA150410JA201-1-1522RV105uMJQ1.rsem.genes.norm_counts.hugo.tab

Under Preview the Normalization is "Quantile normalized counts", but under Review the Data type is "Quantile normalized counts log2(x+1)" . Inconsistency?

**Comment by mokolodi1** [comment]
This is a wrangler problem and should be under that repo or under the
parent repo.
