### ISSUE TITLE
Share button forms are broken

### ISSUE THREAD

**Issue by mokolodi1** [UCSC-MedBook/MedBook-PatientCare#15]
Something is wrong with the AutoForm code rendering the collaboration list in the `editCollaborationsModal` template... The same problems appears when loading the AutoForm when editing the admins/collaborators in a collaboration. 

The options seem to be loading fine and the form isn't rendered until the options are shown. I can't recreate this locally but it's a problem on production.

**Comment by tedgoldstein** [comment]
Can you switch this from autoforms to a normal template?

**Comment by mokolodi1** [comment]
I think the bug is some simple thing... One possible explanation is that I have to change a semantic-ui setting to load the correct Javascript to handle dropdowns.

**Comment by mokolodi1** [comment]
Fixed! https://github.com/UCSC-MedBook/patient-care/commit/1fb3664fc3cf2d8d455f2172e3d5e2c952da22a2
