### ISSUE TITLE
store outlier analysis computation for background cohorts and reuse

### ISSUE THREAD

**Issue by e-t-k** [UCSC-MedBook/MedBook-PatientCare#21]
when outlier analysis is run, store the calculations for the background cohort and re-use them when another outlier analysis is run with the same background cohort.

**Comment by mokolodi1** [comment]
Available in the next branch

**Comment by e-t-k** [comment]
Available on JobRunner master here: https://github.com/UCSC-MedBook/MedBook-JobRunner/commit/3def33dd8edf0f34d3f49ae672c21616f49b3f89

and was pushed to prod at some point in the past week, not sure when.
