### ISSUE TITLE
cannot create more than one sample label when creating dataset

### ISSUE THREAD

**Issue by rbaertsch** [UCSC-MedBook/MedBook-PatientCare#22]
Should be able to paste multiple sample names when creating a dataset.

See hall of shame on slack for more details and workaround

**Comment by e-t-k** [comment]
newline delimited? 
Right now sample name schema doesn't restrict any characters (see newSampleLabel in methods.js) but in practice we're not going to see newlines within the label.

**Comment by mokolodi1** [comment]
The long-term fix is a paste-in UI but for now I'm going to say we should have a Wrangler for this

**Comment by mokolodi1** [comment]
There's a Wrangler for sample labels now. Not sure when I added that, but it exists! I believe that solves this issue.
