### ISSUE TITLE
Sample Group query filter -- use Metadata table (or new Forms?) instead of sample CRF

### ISSUE THREAD

**Issue by e-t-k** [UCSC-MedBook/MedBook-PatientCare#26]
`getSamplesFromFormFilter` Meteor method takes a `sampleCrfId`

this is the ID of a CRFs document which has a CRF field containing the name of the CRF that we use to filter the samples. However the document itself is really just a CRF record pertaining to a specific sample.

This is non ideal. Should determine a reference to the CRF as a whole (how is this implemented in Teo's new data model?) and use that instead.

**Comment by e-t-k** [comment]
querybuilder code is now in `next` branch & working with new forms.

**Comment by mokolodi1** [comment]
Aaand now it's on master!
