### ISSUE TITLE
Sample Group query filter -- Only works when field values are strings

### ISSUE THREAD

**Issue by e-t-k** [UCSC-MedBook/MedBook-PatientCare#27]
Right now all the "possible values" for a form field in the querybuilder table get converted to a string for display; however original field values can technically be any type of object.

So if you query on a value that wasn't originally a string, it will simply find 0 samples.

Use the Metadata collection for each CRF (or whatever Teo's new data model transforms this to) to determine the field value and convert it back when querying.

Also use the Metadata when building the table in the first place; so that instead of a Number-valued field being an (unordered) list of numbers, it's a number-entry field.

**Comment by mokolodi1** [comment]
Currently the clinical wrangler just treats everything as a string and we have no UI for selecting type, so I don't think this is too much of a problem until the clinical wrangler gets updated.

**Comment by mokolodi1** [comment]
We'll re-open this when we have non-string type fields. (Honestly this issue will likely just be one of the things on that feature roadmap.)
