### ISSUE TITLE
Automatically filter sample group before running outlier analysis

### ISSUE THREAD

**Issue by mokolodi1** [UCSC-MedBook/MedBook-PatientCare#31]
Run Yulia's two filtering scripts on the data set before calculating the outlier thresholds.

**Comment by e-t-k** [comment]
Python scripts provided by Yulia . This is to harmonize with what tumormap is doing. See emails.

-- Filter out all the genes that are not expressed in 80% of the samples. 
-- Variance filter: filter out 20% of genes with lowest variance

**Comment by e-t-k** [comment]
This is being tracked in #29 .
