### ISSUE TITLE
Linked objects not deleted

### ISSUE THREAD

**Issue by mokolodi1** [UCSC-MedBook/MedBook-PatientCare#32]
When someone deletes an object, the linked objects aren't deleted (Blobs, GenomicExpression)

**Comment by e-t-k** [comment]
Is the following an accurate elaboration of what you've just said? : 

Some objects (eg Blobs, GenomicExpression have a security model based on being "linked" to other objects. For example, a Sample Group (which has collaboration security) might have a Blob linked to it; that Blob is available to the collaborations of the Sample Group.

When a collaboration-secured object is deleted, none of its linked objects are deleted. This may result in an object that remains in the database but is not available to any collaboration.

---

A linked object can be linked to multiple collaboration-secured objects, right? In which case we shouldn't automatically delete them when their link-ee is deleted, or the other link-ees would end up with them inappropriately removed.

**Comment by mokolodi1** [comment]
Yes!

**Comment by mokolodi1** [comment]
fixed on develop

**Comment by e-t-k** [comment]
If a Blobs2 object is linked to object A, is it allowed to then be linked to object B as well?

**Comment by mokolodi1** [comment]
No. If that becomes a requirement, we could make `associated_object` an
array.

**Comment by e-t-k** [comment]
Great!
