### ISSUE TITLE
Implement UI to create a data set document

### ISSUE THREAD

**Issue by mokolodi1** [UCSC-MedBook/MedBook-PatientCare#4]

**Comment by mokolodi1** [comment]
the URL for this should be `/patient-care/create-data-set`

**Comment by e-t-k** [comment]
By "data set" you mean the data set document that is the new version of the study document.

This is a ui for a user to create a new data set document. User must specify the following things:
-- name
-- description
-- collaborations
They don't need to specify what samples are in the data set.

**Comment by mokolodi1** [comment]
Perfect.
