### ISSUE TITLE
Send to GSEA button on OutlierAnalysis page

### ISSUE THREAD

**Issue by mokolodi1** [UCSC-MedBook/MedBook-PatientCare#40]
We need someone like Holly, Olena, Sofie, or Robert to give us the GSEA command we should run for that.

The other (better) option is to just integrate the GSEA run with the outlier analysis and show the results on the same page.

**Comment by rbaertsch** [comment]
this is why you make adapters.  Both Limma and outliner produce a rank list of genes (also known as a signature).  There are dozens of tools that produced a ranked list of genes. For example DESeq. We should change limma and outlier to save the data into the signature format. Then gsea reads the ranked list from mongo. Now you can mix and match and of these tools.  limma-> GSEA is a pipeline that is frozen and not flexible. Better to run each tool by itself.  Someday we can make a chaining tool that will allow compatible tools to be chained. Fancy but not needed right now.

**Comment by mokolodi1** [comment]
The thing I was talking about was the fact that I don't know what arguments to give GSEA. The outlier analysis produces a list of genes but is not ranked.

**Comment by rbaertsch** [comment]
The outliner analysis produces a score for each gene, correct? Use that to sort the list.

**Comment by mokolodi1** [comment]
Done.
