### ISSUE TITLE
Should print a log statement when someone logs in

### ISSUE THREAD

**Issue by mokolodi1** [UCSC-MedBook/MedBook-PatientCare#48]
This change will occur in the collaborations package I believe.

**Comment by rbaertsch** [comment]
I think it should be in an audit log collection so It can be searched easily

**Comment by mokolodi1** [comment]
I think we'll need to think hard about what kind of audit log we'll want before we implement something like that. For now this'll do. Should we be tracking users, @rcurrie and @tedgoldstein?

**Comment by rbaertsch** [comment]
To get continued funding, you will have to prove that people are using the system and which parts. Perhaps the most important feature.

**Comment by rbaertsch** [comment]
You could use google analytics but the granularity is not as good.

**Comment by rcurrie** [comment]
For now/this sprint let's leave it at this. Once we have a few more tools in production and users we can look at putting a better tracking system in place against other priorities.

**Comment by tedgoldstein** [comment]
Good enough for now.  In the future, it would be good to conform to Apache Log File Format so that we can use the great Log File Analyzers.

**Comment by mokolodi1** [comment]
Done. More advanced logging can wait for another time.
