### ISSUE TITLE
Limma/GSEA errors need explanation

### ISSUE THREAD

**Issue by mokolodi1** [UCSC-MedBook/MedBook-PatientCare#50]
We need to show the stderr and stdout of the failed command on the result page. We'll do that by saving the files as blobs and subscribing to them on the client so they have a nice list of files to download.

**Comment by rbaertsch** [comment]
:+1:

**Comment by mokolodi1** [comment]
This is part of this PR: https://github.com/UCSC-MedBook/MedBook_/pull/36
