### ISSUE TITLE
Generalize the Limma/GSEA route for navigating folder-like routes

### ISSUE THREAD

**Issue by mokolodi1** [UCSC-MedBook/MedBook-PatientCare#53]
We need to be able to navigate multi-level folder structures. I'm not sure if the GSEA output has this, and if not we'll save this until we need it.

**Comment by tedgoldstein** [comment]
Yes. GSEA has a collection of folders. I have not seen the folders nested. 

Ted

**Comment by mokolodi1** [comment]
One level was good enough for GSEA.
