### ISSUE TITLE
[user request] share multiple outlier analyses with 1 click

### ISSUE THREAD

**Issue by e-t-k** [UCSC-MedBook/MedBook-PatientCare#78]
As Linh describes it:
She would like to be able to select multiple completed outlier analyses (for example, via a checkbox next to each 'share' button) and then use the sharing interface once to share all of the selected analyses with the desired collaboration.

Currently the sharing interface must be used individually for each analysis.

**Comment by rcurrie** [comment]
Before we add a ton of checkbox’s I’d like to do a bit more ‘customer’ research. It may be the case that projects like CKCC want to just share with everyone in the collaboration automatically vs. forcing them to click a ton.

**Comment by e-t-k** [comment]
Agreed. 
We had a previous discussion about inheriting collaboration automatically (eg, if both the sample & the reference cohort are visible to CKCC, the analysis is too). The outcome of that was thinking that we didn't want everyone's outlier analysis log to be "cluttered" by a ton of random analyses that other people had done.

This is also messy bc the collaboration architecture has no notion of "ownership" of objects as separate from "viewership" (although Teo wants to add this) -- when I make X visible to you, you have identical privileges over it to mine.

**Comment by mokolodi1** [comment]
The original issue here is live on production (multi-select for jobs), and the inheriting sharing automatically is addressed in https://github.com/UCSC-MedBook/MedBook_/pull/67.
