### ISSUE TITLE
Can't create a sample group with > 1 data set.

### ISSUE THREAD

**Issue by e-t-k** [UCSC-MedBook/MedBook-PatientCare#85]
This line is filtering on _id when it should be filtering on data_set_id.
So uniq.length will always be 1. 

https://github.com/UCSC-MedBook/patient-care/blob/d806e7f70472a7a1ecd562fd32ca3e450cd5d2f0/webapp/server/methods.js#L147

**Comment by mokolodi1** [comment]
NOTE: @e-t-k gets credit for handling fixing this issue.
