### ISSUE TITLE
Sample group mangement page -- add sample group version number to left side menu

### ISSUE THREAD

**Issue by e-t-k** [UCSC-MedBook/MedBook-PatientCare#86]
Version # is currently visible for selected sample group, but not for the sample group list on the left.

**Comment by mokolodi1** [comment]
Building, soon to be live on staging.

**Comment by mokolodi1** [comment]
<img width="415" alt="screen shot 2016-08-17 at 4 39 48 pm" src="https://cloud.githubusercontent.com/assets/1329343/17757094/4200d00c-6499-11e6-9202-be40f630dd50.png">

**Comment by mokolodi1** [comment]
Fixed the not-being-lined-up thing!
