### ISSUE TITLE
Common normalization process

### ISSUE THREAD

**Issue by tedgoldstein** [UCSC-MedBook/MedBook-PatientCare#91]
We need a way to compare RNAseq datasets from different projects.  There are two things which need to happen:
1. Normalization to a common distribution and scale such as the Z score or rank normal.
2. Combat batch correction.

Both of these things require bioinformatician oversite.

**Comment by rbaertsch** [comment]
Step three is the run before/after QC reports to check that the batch effect has been minimized for the variable that you are interested in looking at. This is impossible to solve in the general case.

**Comment by mokolodi1** [comment]
I agree with Robert that this is very difficult if not impossible to solve in the general case.

If necessary, a feature request (GitHub issue) should be made detailing the exact tools to be added to facilitate normalization to a common distribution and batch correction.
