### ISSUE TITLE
WHen making data sets, allow "other" option for eg quantification method

### ISSUE THREAD

**Issue by e-t-k** [UCSC-MedBook/MedBook-PatientCare#96]
Olena just made a data set for a patient that was neither `RSEM` nor `Cufflinks` . She picked RSEM, but this is obviously inaccurate. Allow for stuff that we didn't expect!

**Comment by mokolodi1** [comment]
What was the quantification method? We can add an "Other" method!

**Comment by mokolodi1** [comment]
Olena/@e-k-t meant normalization.

> It was RPKM or FPKM

Adding that now.
