### ISSUE TITLE
Adds icons to display DGIdb drug next to gene names

### ISSUE THREAD

**Issue by rcurrie** [UCSC-MedBook/MedBook-PatientCare#98]
Crossed DGIdb postgres db with the list of FDA drugs Linh gave me (repo https://github.com/rcurrie/medbook-dgidb for future reference)

Out of 18208 drugs listed in fda_drugs.csv I found 9614 unique ones. Of those I found 528 drugs that have a gene association in DGIdb. For example:
ACETAMINOPHEN   CYP2D6  FAAH    PTGS1   PTGS2   SULT1A1 TRPV1
Which seems to match DGIdb.

**Comment by tedgoldstein** [comment]
There is also http://www.drugbank.ca/

**Comment by rcurrie** [comment]
Good news - its already included in DGIdb, in fact it as 15 sources:

http://dgidb.genome.wustl.edu/sources

**Comment by rcurrie** [comment]
Added to production
